### ISSUE TITLE
Could you make it so absorption is an overlay as well, and doesn't create a new row?

### ISSUE THREAD

**Issue by Foozey** [Terrails/HealthOverlay#12]

**Comment by Terrails** [comment]
How exactly do you expect this to display? Should it add hearts with `absorptionColors` after the health or should it use the same color as health and extend it while absorption is active? With the latter there's no way to differentiate between absorption and health, so I am guessing that you want the former.

**Comment by Foozey** [comment]
Basically, the absorption bar would replace the health bar for the amount of absorption given. For example, if there were two hearts of absorption, the first 2 hearts of the normal health bar would be replaced with the absorption hearts while the effect is active. If there were 8 hearts of absorption, the first 8 hearts would be replaced, etc. If there's an amount of absorption over the max, that's when the absorption overlays that you've added kick in. You get the idea.

**Comment by Terrails** [comment]
Oh, so that simple. That'll be a really easy change then.
