### ISSUE TITLE
Rendering Overlay

### ISSUE THREAD

**Issue by Coraline77447** [Terrails/HealthOverlay#19]
Minecraft: 1.17.1
Health Overlay: 3.0.2
Forge: 37.0.22
Optifine Installed?: No (Not compatible with forge 1.17 yet)
Crash Report: https://pastebin.com/XKmMWihH
Log: [latest.log](https://github.com/Terrails/HealthOverlay/files/6924175/latest.log)

**Comment by Terrails** [comment]
Found the issue  
```[06:50:35] [modloading-worker-1/ERROR]: Absorption effect colors must either be empty or have 2 values.```
One of your absorption effect colours are probably empty and the code is currently only working with 2 values. I'm unfortunately not able to fix it currently so for now you can just give it 2 colours. There are defaults but it may require deleting the config file.
