### ISSUE TITLE
More of a request

### ISSUE THREAD

**Issue by JuceDoesThings** [Terrails/HealthOverlay#21]
One major issue with this pack is the learning curve. For example, if someone has 3 bars, they may not be able to differentiate 2 from 3. I think a good solution to this would be to, configurably, have health displayed numerically as well as visually. That way you could have it yellow while showing your HP as smth like "XX/60" or whatever, you get the point

**Comment by Terrails** [comment]
This is a nice idea, but I'm having a hard time finding a good location to display this health number. There must be a mod that displays your health as a number somewhere on screen already. 
I'll put this on my list, but if you find a mod that has the feature, I would prefer if you used that instead as my main focus with this mod is just to colorize and unify hearts.

**Comment by Pogtree** [comment]
nice

**Comment by jklw10** [comment]
there was one mod like this that just showed the current /max health in a larger heart next to the health bar.

**Comment by Terrails** [comment]
![java_2022-06-18_11-24-18_Unq0](https://user-images.githubusercontent.com/8273440/174431496-f281316e-1c9f-45f0-bd15-e1e9900822cb.png)
I implemented something like this for both absorption and health, the text color and content can also be changed within the config files.

Just have to port it over from 1.17 to 1.18 and I'm gonna have a release ready. Then its time to start work on 1.19.
