### ISSUE TITLE
game crash when the mod is installed

### ISSUE THREAD

**Issue by remidu64** [Terrails/HealthOverlay#23]
when the mod is installed, the game crashes instantly
logs:
[latest.log](https://github.com/Terrails/HealthOverlay/files/7020541/latest.log)

is optifine installed ? : no
version used : 1.17
mod loader: fabric

**Comment by Terrails** [comment]
Can't seem to reproduce this. Launches fine on my end, I can only suggest you to the new version, but it works fine on the previous version. You seem to have a lot of mods installed so it might not even be Health Overlay's fault as there isnt a crash at the end of the log.

**Comment by red2blue** [comment]
crash happens to me as well.. had to revert to last version
