### ISSUE TITLE
[bug 1.17.1 fabric] armor is shown two rows above health level when gaining 11 or more hearts

### ISSUE THREAD

**Issue by TobiPeterG** [Terrails/HealthOverlay#24]
Hey there,

when gaining 11 or more hearts, the armor row goes 1 row up, leaving one row of empty space.

[https://ibb.co/k4Jq5Sx](url)

health overlay was next to health levels the only mods I had active, so no other mod could have caused this

**Comment by Terrails** [comment]
Already fixed in 4.0.2. Seems like its not in the app, weird. Gonna have to wait for CurseForge to do its sync thing or download from the website.
