### ISSUE TITLE
Armor display sitting where its not supposed to 2.0

### ISSUE THREAD

**Issue by KaneHart** [Terrails/HealthOverlay#28]
Hi it seems Bug #22 is back with "HealthOverlay-1.18.1-6.0.0.jar" for Fabric. I can't confirm if it could be caused by another mod I did not have time to go through it yet, but I can tell you looked exactly the same as the old report.

Thanks :)

**Comment by Terrails** [comment]
It has been fixed a few hours after 6.0.0. Check out 6.0.1

**Comment by KaneHart** [comment]
Opps you were a fast one haha :) Thanks
