### ISSUE TITLE
Freezing Effect not working as intended [FABRIC HealthOverlay-1.17.1-4.0.2]

### ISSUE THREAD

**Issue by JuceDoesThings** [Terrails/HealthOverlay#29]
For some reason, the freezing effect is working... oddly. While the other effects (poison and withering) work fine even with absorption, freezing has a weird texturing issue that makes it just look messy. Not only that, but for some odd reason it seems to have a color to it even at 20hp and doesn't ever change properly. It starts as a dark blue, turns purple, and just cycles through those colors forever
![image](https://user-images.githubusercontent.com/85078618/148661615-4f0d7ef7-c6cf-4ff5-a068-f65dff2dc817.png)

**Comment by Terrails** [comment]
The colors are supposed to cycle between health rows, the same happens with poison and withering. There are 2 poison, withering and freezing colors that are cycled through for each row of health. You are allowed to define only one color to use vanilla and that color, so you will have vanilla frozen hearts at 20, 60, 100... and the defined color at 40, 80, 120 hp.
