### ISSUE TITLE
1.18.2 update?

### ISSUE THREAD

**Issue by FederAndInk** [Terrails/HealthOverlay#30]
is it possible to update to 1.18.2? :)

**Comment by Terrails** [comment]
The latest 1.18.1 version works on 1.18.2. Just changed the required version on the files, so it should be available in the app shortly.

**Comment by FederAndInk** [comment]
Thanks ^^
Its often the case, but the modpacks can't depend on it if it's not repackaged/rebuild for 1.18.2
