### ISSUE TITLE
1.19 Fail to load correctly

### ISSUE THREAD

**Issue by Sanastae** [Terrails/HealthOverlay#33]
Hi,
I would add this mod on a custom forge modpack. When launching the game I have this error
```
Health Overlay (healthoverlay) has failed to load correctly
    java.lang.NoClassDefFoundError: net/minecraftforge/client/event/RenderGameOverlayEvent$PreLayer
```

There is my crashreport: [crash-2022-07-22_11.09.39-fml.txt](https://github.com/Terrails/HealthOverlay/files/9166408/crash-2022-07-22_11.09.39-fml.txt)

**Comment by Terrails** [comment]
Uploaded a fix to curseforge, should be available in a bit.
