### ISSUE TITLE
[Suggestion] Heart colors

### ISSUE THREAD

**Issue by INooBTooMuch** [Terrails/HealthOverlay#34]
It would be good if the heart colors didn't loop. If the heart count has gone above the max that has been configured to have a color it shouldn't loop back to vanilla and allover again.
Maybe people don't want this, so make a config about loop being on/off?

(If this already exists I didn't find it in the config files, sorry)

Minecraft : 1.18.2
Forge : 40.1.68
HealthOverlay : 6.2.4

**Comment by Terrails** [comment]
What should happen if health goes above the last heart color then?

**Comment by INooBTooMuch** [comment]
Sorry for the late reply.
It should stay as the last color that is configured, if the last row of harts is white it should be white for the rest rows instead of going back to red (vanilla)

**Comment by Terrails** [comment]
If I were to do that the rows would not be recognizable, as the both rows would be the same color.

**Comment by INooBTooMuch** [comment]
Yes but there are ways to add your own colors on even more rows and there is a way to show the number on the left. Plus it should be configurable if it is possible.

**Comment by Terrails** [comment]
I'm sorry but I really don't see a use for this. The hearts not changing would just raise red flags to regular users. If you need more colored hearts, you should just add enough to hit the limit you need. For all other cases the colors looping back is understandable.

**Comment by INooBTooMuch** [comment]
If I add the last color multiple times after the last row would it be what I want or would it crash something?

**Comment by Terrails** [comment]
It would do the thing you want.
