### ISSUE TITLE
[incompatibility] Victus - crash at startup

### ISSUE THREAD

**Issue by ruyanve** [Terrails/HealthOverlay#37]
Don't ask my why I tried these two together, but here we are.
[Victus](https://www.curseforge.com/minecraft/mc-mods/victus)

[crashlog](https://hastebin.com/enurivebih.yaml)

**Comment by Terrails** [comment]
Seems to be a conflicting mixin injection error. I'll try to see if there's a workaround.

**Comment by Terrails** [comment]
I'm going to mark this as unplanned as it would be a huge effort to try and make these two compatible. The thing is that Victus injects code in the middle of vanilla heart rendering, which Health Overlay completely cancels. Finding a way around this is kind of annoying. It's a really odd issue, but I might play around with it in the future, if I ever want to make the mod more friendly with other mods.
