### ISSUE TITLE
[Compat 1.18.2] Infernal Expansion Compatibility

### ISSUE THREAD

**Issue by SaltSouls** [Terrails/HealthOverlay#38]
Infernal Expansion add an effect called Infected which has it's own heart overlay which unfortunately it isn't compatible with this mod and causes the hearts to render incorrectly.

**Comment by Terrails** [comment]
Unfortunately it is not possible as Infernal Expansion follows vanilla render behavior with separate rows. Compatibility would have to be implemented on their side.
