### ISSUE TITLE
Hearts displayed in Tab don't have the overlay

### ISSUE THREAD

**Issue by Essermark** [Terrails/HealthOverlay#4]
![image](https://user-images.githubusercontent.com/65592600/87246272-aec90b00-c48f-11ea-9c2e-8687f2526eed.png)
![image](https://user-images.githubusercontent.com/65592600/87246348-344cbb00-c490-11ea-8ce4-bae060b8da85.png)
This is a singleplayer world in 1.16.

**Comment by Terrails** [comment]
I didn't think of this case at all, I'll get around to doing it in the coming days. Thanks for the reporting it! The issue probably happens in every version, since I didn't touch the tab overlay.

**Comment by Essermark** [comment]
Glad I could help! Would you be adding this to previous versions as well or just 1.16+?

**Comment by Terrails** [comment]
Most likely 1.14+

**Comment by Essermark** [comment]
That's good, thanks.

**Comment by Terrails** [comment]
This should do. I only did 1.15 and 1.16 because I forgot that I already deleted the workspace for 1.14. I'll also look into doing the same thing on forge, if its even possible. But I doubt that it'll be possible without some hook though.

**Comment by Terrails** [comment]
Also some additional info on what I did. Since you can only access the "score" value, I couldn't make a separate renderer for absorption and for the health, instead the hearts are all rendered with the colors for the hearts from the hotbar. I might add a separate config option for those hearts in the future.

**Comment by Essermark** [comment]
Sadly, after updating the mod (3.6.11) the issue still seems to be present.
Also when the player's health reaches 44 the game stops rendering the hearts altogether:
![image](https://user-images.githubusercontent.com/65592600/87650451-053a9000-c795-11ea-9e14-76c26ea380ef.png)
Which would make the health overlay in the player list redundant when players have 44+ health.

**Comment by Terrails** [comment]
Oh, the feature works only in dev. Seems that something is broken with mixins/fabric. I'll look into it.

**Comment by Terrails** [comment]
Alright, it should be fixed now. Tell me if it works when you have time to check it out

**Comment by Essermark** [comment]
Yeah, It works like a charm, thanks!
