### ISSUE TITLE
(Issue) Crashing when at launch

### ISSUE THREAD

**Issue by asteroidb12** [Terrails/HealthOverlay#41]
Hello,
This mod when enabled with other mods crashes with exit code 1 at start, I do not know which mods conflict in error with each other than these recently downloaded mods.

Latest log:
https://mclo.gs/mEUv0dz

Downloaded Mods (checkmark = activated):
![image](https://user-images.githubusercontent.com/68461874/202822735-841c7adc-c4f2-4344-9b93-33f821dc8095.png)

Full Modlist:
![image](https://user-images.githubusercontent.com/68461874/202821501-a197a16f-d89c-4ed5-8e47-99e0f910e574.png)
![image](https://user-images.githubusercontent.com/68461874/202821512-a34c9dad-c028-4155-9a2b-f43f7d065c05.png)

Thank you for reading.

**Comment by Terrails** [comment]
The crash report has nothing to do with health overlay.
