### ISSUE TITLE
compatibility with Player health Indicators

### ISSUE THREAD

**Issue by slovinsqui** [Terrails/HealthOverlay#42]
Extra hearts don´t have different color when rendered above the player, would be nice if it did c:

player health indicators mod 
https://www.curseforge.com/minecraft/mc-mods/player-health-indicators

**Comment by Terrails** [comment]
Unfortunately cannot do that :/. 
Mods like health indicators would need to know if health overlay is present (and active) and basically replicate the same behavior. I would not bug the developer of health indicators about this, as it can be annoying to implement (especially with no API from the other mod). I might look into writing some kind of API for easier access to the current heart icons, which other mods would then use, but its not really high priority.
