### ISSUE TITLE
Hearts removed with enchanted armor don't adjust

### ISSUE THREAD

**Issue by Jaeiya** [Terrails/HealthOverlay#5]
I have an enchantment mod that expands enchanting. One of the enchantments is vitality which increases the hearts of the wearer; however if that piece of armor is removed, the hearts do not adjust. This causes the game to think you have negative hearts and therefore if you take any damage at all, you get killed.

**Comment by Terrails** [comment]
This shouldn't be caused by HealthOverlay. It's a client sided mod. It can't modify your "real" health. You should go and report it to that mod's issue repo.

**Comment by Jaeiya** [comment]
Except without your mod, the hearts are added and removed as expected. How do you explain that?

**Comment by Terrails** [comment]
Looks like a client side sync issue on their end. They're probably changing the MAX_HEALTH attribute on server side only without doing it on both sides or syncing it. So the sync currently happens when the health gets changed via damage or something else.

**Comment by Jaeiya** [comment]
Thanks, I'll take up the issue with the mod author.
