### ISSUE TITLE
Incompatible with Enchancement

### ISSUE THREAD

**Issue by SplendidAlakey** [Terrails/HealthOverlay#50]
**MC** 1.19.2
**[Enchancement](https://www.curseforge.com/minecraft/mc-mods/enchancement/files/4398114)** 1.2
**Health Overlay** 7.2.3

When Health Overlay is installed together with the [newest version of Enchancement](https://www.curseforge.com/minecraft/mc-mods/enchancement/files/4398114), the game crashes on startup.

Originally reported to Enchancement, but was told to report here, instead: https://github.com/MoriyaShiine/enchancement/issues/82#issuecomment-1432598360

**Comment by Terrails** [comment]
I will upload the update to CurseForge in a bit. Currently this allows both mods to coexist together without any errors. The only issue is that the Brimstone enchantment will not display the heart bar in the middle of the screen while readying the crossbow. I have opened a different issue (#51) addressing this and will work on it. Cannot give an exact time when it will be done.
