### ISSUE TITLE
[Modrinth] Could you upload your mods on modrinth?

### ISSUE THREAD

**Issue by xR4YM0ND** [Terrails/HealthOverlay#54]
It would be awesome to fully this mod in our modpack there.

**Comment by Terrails** [comment]
I am currently busy irl until the middle of next month and have also started a rewrite of the mod. This may take a bit but I'll look into it.

**Comment by Terrails** [comment]
I have gotten some time and have finished and uploaded the rewrite under [Colorful Hearts](https://modrinth.com/mod/colorful-hearts). The rewrite is as basic as possible with just colored hearts and will not have any kind of heart bar movement that was present in health overlay as it just complicated things which made mod compatibility a nightmare. If colored hearts are all you need then it is perfect and will stay that way!
