### ISSUE TITLE
hearts added via the health boost command don't show for me

### ISSUE THREAD

**Issue by hackaholic5069** [Terrails/HealthOverlay#6]
![2020-07-21_23 52 41](https://user-images.githubusercontent.com/37553921/88150337-bb471500-cbad-11ea-9e3e-71de0dd7afc3.png)

**Comment by Terrails** [comment]
A [link](https://minecraft.gamepedia.com/Health_Boost) to gamepedia.
"however the entity's actual health is not decreased to the new maximum until damaged or healed"
I just tested it and it works without any issues. You just have to heal. The effect doesn't work like absorption where it just adds health straight away.
