### ISSUE TITLE
[1.14, 1.15, 1.16] Health Overlay causes FML to display all servers as incompatible in multiplayer menu.

### ISSUE THREAD

**Issue by Vaelzan** [Terrails/HealthOverlay#8]
See here for reference: https://mcforge.readthedocs.io/en/1.15.x/concepts/sides/#writing-one-sided-mods

Client-sided Forge mods should include 
`ModLoadingContext.get().registerExtensionPoint(ExtensionPoint.DISPLAYTEST, () -> Pair.of(() -> FMLNetworkConstants.IGNORESERVERONLY, (a, b) -> true));` inside their constructor. This is missing for every Forge version of Health Overlay, and will therefore cause a red X to display on the multiplayer menu screen when trying to connect to any server that does not have the mod. Since the mod crashes on dedicated servers (which is also a bug - it should do nothing at all. No client-sided mod should crash a server by being present), this is all of them.

**Comment by Terrails** [comment]
It should be fixed now.
