### ISSUE TITLE
[1.16.4] Dedicated Server Crash

### ISSUE THREAD

**Issue by TwilightPSN** [Terrails/HealthOverlay#9]
The mod causes a crash when its on a dedicated server.

https://gist.github.com/TwilightPSN/1a712e91e60d9f33df15068156ab4fc2

**Comment by Terrails** [comment]
It's an easy fix, but why would you ever have this mod on a dedicated server? It's specifically a client only mod.

**Comment by TwilightPSN** [comment]
When mass updating a server I just throw all the mods up its also easier for newer people who haven’t really hosted servers before

**Comment by Terrails** [comment]
It should be available on CurseForge in a few mins.
